# Determines how to notify players when there is a Tzeva Adom.
# Multiple notifiers can be used, separated by a comma.
server-notifier: title, sound

# This section configures the behavior of the notifiers.
notifiers:
    title:
        title: '&c&l> &4%title% &c&l<'
        subtitle: '&cצבע אדום ב&4&l%region%'
    
    # The 'alternative' sound is used when the server's version doesn't have the sound of 'value'.
    sound:
        value: 'BLOCK_BELL_USE'
        alternative: 'BLOCK_NOTE_BLOCK_HARP'
        amount: 7